template_path: admin-accounts.template
parameters:
  UserName: adminUser1
  Password: 2js&!!sCC
  Group: !stack_output preprod/admin-group.yaml::AdminGroup
hooks:
  after_create:
  - !cmd "sceptre list outputs preprod/admin-accounts.yaml"